# Add a theme to the portfolio.
theme: Jekyll-theme-cayman

# List of themes to try:
# minima -  basic but ok
# cayman - No
# hacker -  No, too dark
# slate - Dark but might be ok.
# Architect - ?
# primer - ?
# Time Machine - No
# Modernist - Maybe, ?
# Leap day - No
